// #define AAA_THIS_IS_A_EUPHORIA_PATCHES_SETTINGS_FILE
// #define AAB_FOR_EUPHORIA_PATCHES_VERSION_1_6_0

#ifdef AAA_THIS_IS_A_EUPHORIA_PATCHES_SETTINGS_FILE
#endif
#ifdef AAB_FOR_EUPHORIA_PATCHES_VERSION_1_6_0
#endif